[global]
    workgroup = LAB
    realm     = LAB.LOCAL
    netbios name = DC1
    server role = active directory domain controller
    dns forwarder = 8.8.8.8

    # Intentional: weak password policy
    min password length = 1
    password complexity = off

    # Intentional: LDAP anonymous bind allowed
    ldap server require strong auth = no
    ldap anonymous auth  = yes

    # Intentional: NTLM auth enabled (legacy)
    ntlm auth = yes
    lanman auth = yes
    client lanman auth = yes

    log level = 1
    log file  = /var/log/samba/log.%m

[sysvol]
    path = /var/lib/samba/sysvol
    read only = No

[netlogon]
    path = /var/lib/samba/sysvol/lab.local/scripts
    read only = No

[public-share]
    path = /srv/samba/public
    browseable = yes
    read only = no
    guest ok = yes
    comment = Intentional: anonymous-accessible share
